# Copyright (c) 2017 Dell EMC.
---
galaxy_info:
  author: Dell EMC Networking Engineering
  description: This sample role facilitates the configuration of MAC table supported using CPS API in OPX. 
  license:  Apache 2.0
  min_ansible_version: 2.2

  platforms:
  - name: OPX

  galaxy_tags:
    - Networking
    - OPX
    - Openswitch
